
# Site settings
title: theTizzo was here
description: >
  This a fancy blog that is for fancy code.
url: "https://thetizzo.com"
avatar: "true"
permalink: /:categories/:year/:month/:day/:title
bio: >
  Hi, my name is Jason &amp; I'm a developer who builds parts the Internet in mostly Ruby &amp; Rails.  This
  is my blog which contains my, hopefully well-thought-out, solutions to some of the interesting problems I
  have encountered.

# Social Links
social_links:
  github_url:            "https://github.com/thetizzo"
  twitter_url:           "https://twitter.com/thetizzo"
  linkedin_url:          "https://www.linkedin.com/in/thetizzo"
  # resume_url:            "/resume"

# Resume settings
resume:
  name:                    "Jason Taylor"
  title:                   "Software Engineer"
  contact_email:           "resume@thetizzo.com"

  looking_for_work:        "no"

  # sections
  section_experience:      true
  section_education:       true
  section_projects:        true
  section_skills:          true
  section_links:           false

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-gist

destination: public
exclude: ["CNAME", "Rakefile", "README.md", "public"]
