# Site settings
title: theTizzo was here
# email: your-email@domain.com
description: >
  This a fancy blog that is for fancy code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thetizzo.com" # the base hostname & protocol for your site
twitter_username: thetizzo
github_username:  thetizzo

# Build settings
markdown: kramdown
