
# Site settings
title: theTizzo was here
description: >
  This a fancy blog that is for fancy code.
baseurl: ""
url: "http://thetizzo.com"
avatar: "true"

# Social Links
social_links:
  github_url:            "https://github.com/thetizzo"
  twitter_url:           "http://twitter.com/thetizzo"
  linkedin_url:          "https://www.linkedin.com/in/thetizzo"
  
# Resume settings
resume_name:                    "Manrock"
resume_title:                   "Earth Crusher"
resume_contact_email:           "j.m.taylor1@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
# resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

destination: public
exclude: ["CNAME", "Rakefile", "README.md", "public"]
