
# Site settings
title: theTizzo was here
description: >
  This a fancy blog that is for fancy code.
url: "https://thetizzo.com"
avatar: "true"
permalink: /:categories/:year/:month/:day/:title
bio: >
  Hi, my name is Jason. I'm a web developer who builds parts of the Internet in mostly Ruby &amp; Rails.  This
  blog contains my solutions to some of the interesting problems I have encountered.

# Social Links
social_links:
  github_url:            "https://github.com/thetizzo"
  twitter_url:           "https://twitter.com/thetizzo"
  linkedin_url:          "https://www.linkedin.com/in/thetizzo"
  resume_url:            "/resume"

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-gist

destination: public

exclude: ["CNAME", "Rakefile", "README.md", "public", "Gemfile", "Gemfile.lock"]
