
# Site settings
title: theTizzo was here
description: >
  This a fancy blog that is for fancy code.
baseurl: ""
url: "http://thetizzo.com"
avatar: "true"

# Social Links
social_links:
  github_url:            "https://github.com/thetizzo"
  twitter_url:           "http://twitter.com/thetizzo"
  linkedin_url:          "https://www.linkedin.com/in/thetizzo"
  resume_url:            "http://thetizzo.com/resume"

# Resume settings
resume:
  name:                    "Jason Taylor"
  title:                   "Software Engineer"
  contact_email:           "resume@thetizzo.com"

  looking_for_work:        "no"

  # sections
  section_experience:      true
  section_education:       true
  section_projects:        true
  section_skills:          false
  section_links:           false

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

destination: public
exclude: ["CNAME", "Rakefile", "README.md", "public"]
